agnito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.views import BookDocumentView

admin.site.site_header = "Agnito"
admin.site.site_title = "Agnito"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('superadmin/', include('backend.backend.urls')),
    path('admin-login/', include('login.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('search/', BookDocumentView.as_view({'get': 'list'})),
    path('accounts/', include('allauth.urls')), ### allauth
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from os import name
from django.urls import path, include
from .views import *

urlpatterns = [
    path('contact/', ContactView.as_view()),
    path('login/', LoginView.as_view()),
    path('signup/', SignupView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('social_signup/', SocialSignupView.as_view()),
    path('library/<int:user_id>', LibraryView.as_view()),
    path('library/', LibraryView.as_view()),
    path('popular/', PopularView.as_view()),
    path('banner/', BannerView.as_view()),
    path('wishlist/<int:user_id>/', WishlistView.as_view()),
    path('wishlistAdd/', WishlistView.as_view()),
    path('wishlistDelete/<int:pk>/', wishlist_delete),
    path('category/', CategoryView.as_view()),
    path('payment/', PaymentView.as_view()),
    path('order_cart/', OrderCart.as_view()),
    path('book-detail/<int:pk>/', BookDetailView.as_view()),
    path('book_detail/<int:pk>/', BookDetail.as_view()),
    path('saveNote/', SaveNote.as_view()),
    path('cart-item/<str:cartId>/', CartView.as_view()),
    path('book-listing/<int:pk>/', BookListingView.as_view()),
    path('forget_password/', ForgetPasswordView.as_view(), name='forget-password'),
    path('reset-password-confirm/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', ResetPasswordCompleteView.as_view(),name='reset-password-complete'),
    # path('check_user_login/<int:pk>/', BookListingView.as_view()),
]

backend/banner/urls.py
from django.urls import path, include
from .views import *

app_name = 'banner'

urlpatterns = [
    path('List/', banner_list, name="banner_list"),
    path('Create/', BannerView.as_view(), name="banner_add"),
    path('update/<int:pk>/', BannerView.as_view(), name="banner_edit"),
    path('delete/<int:pk>/', BannerView.banner_delete, name="banner_delete"),
]

backend/book_assign/urls.py
from django.urls import path, include
from .views import *

app_name = 'book_assign'

urlpatterns = [
    path('List/', book_assign_list, name="book_assign_list"),
    path('Assign/', book_assign, name="book_assign"),
    path('<int:pk>/delete/',book_assign_delete, name="book_assign_delete"),
    path('<int:pk>/edit/',book_assign_edit, name="book_assign_edit"),
]

backend/contact/urls.py
from django.urls import path, include
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('List/', ContactListView.as_view(), name="contact_list"),
]

backend/payment/urls.py
from django.urls import path, include
from .views import *

app_name = 'payment'

urlpatterns = [
    path('payment_setting/', payment_setting, name="payment_setting"),
]

templates/main/sidebar.html
{% load static %}
<nav class="sidebar">
    <div class="logo d-flex justify-content-between">
        <!-- <a class="large_logo" href="index-2.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
        <a class="small_logo" href="index-2.html"><img src="{% static 'img/mini_logo.png' %}" alt=""></a> -->
        <a class="large_logo" href="{% url 'superadmin' %}"> <img src="{% static 'img/logo/logo.png' %}" alt=""> </a>
        <a class="small_logo" href="{% url 'superadmin' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>

        <div class="sidebar_close_icon d-lg-none">
            <i class="ti-close"></i>
        </div>
    </div>
    <ul id="sidebar_menu">
<!--            <li class="">-->
<!--                <a class="" href="{% url 'superadmin' %}" aria-expanded="false">-->
<!--                    <div class="nav_icon_small">-->
<!--                        <img src="{% static 'img/menu-icon/dashboard.svg' %}" alt="">-->
<!--                    </div>-->
<!--                    <div class="nav_title">-->
<!--                        <span>Dashboard</span>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="">-->
<!--                <a class="" href="{% url 'teacher:access' %}" aria-expanded="false">-->
<!--                    <div class="nav_icon_small">-->
<!--                        <i class="fa fa-universal-access"></i>-->
<!--                    </div>-->
<!--                    <div class="nav_title">-->
<!--                        <span>Book Access Management</span>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="">-->
<!--                <a class="" href="{% url 'teacher:timing' %}" aria-expanded="false">-->
<!--                    <div class="nav_icon_small">-->
<!--                        <i class="fa fa-clock"></i>-->
<!--                    </div>-->
<!--                    <div class="nav_title">-->
<!--                        <span>Book Timing Management</span>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </li>-->


        <li class="">
            <a class="" href="{% url 'superadmin' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/dashboard.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Dashboard</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'ebook:book_manager' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/11.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Book Manager</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'ebook:get_catalogue_manager' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/8.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Catalogue Manager</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'users:user_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/5.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>User Manager</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'report:report_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/13.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Report Management</span>
                </div>
            </a>
        </li>

         <li class="">
            <a class="" href="{% url 'cat:category_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/8.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Category Management</span>
                </div>
            </a>
        </li>

        <li class="">
            <a class="" href="{% url 'banner:banner_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/2.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Banner Management</span>
                </div>
            </a>
        </li>

        <li class="">
            <a class="" href="{% url 'contacts:contact_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/2.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Contact Manager</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'book_assign:book_assign_list' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/2.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Book Assignment</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'payment:payment_setting' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/dashboard.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Payment Setting</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'users:profile' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/4.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Admin Profile</span>
                </div>
            </a>
        </li>
        <li class="">
            <a class="" href="{% url 'users:change_password' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/4.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Change Your Password</span>
                </div>
            </a>
        </li>
         <li class="">
            <a class="" href="{% url 'logout' %}" aria-expanded="false">
                <div class="nav_icon_small">
                    <img src="{% static 'img/menu-icon/dashboard.svg' %}" alt="">
                </div>
                <div class="nav_title">
                    <span>Log Out</span>
                </div>
            </a>
        </li>
    </ul>
</nav>