agnito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.views import BookDocumentView

admin.site.site_header = "Agnito"
admin.site.site_title = "Agnito"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('superadmin/', include('backend.backend.urls')),
    path('admin-login/', include('login.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('search/', BookDocumentView.as_view({'get': 'list'})),
    path('accounts/', include('allauth.urls')), ### allauth
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from os import name
from django.urls import path, include
from .views import *

urlpatterns = [
    path('contact/', ContactView.as_view()),
    path('login/', LoginView.as_view()),
    path('signup/', SignupView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('social_signup/', SocialSignupView.as_view()),
    path('library/<int:user_id>', LibraryView.as_view()),
    path('library/', LibraryView.as_view()),
    path('popular/', PopularView.as_view()),
    path('banner/', BannerView.as_view()),
    path('wishlist/<int:user_id>/', WishlistView.as_view()),
    path('wishlistAdd/', WishlistView.as_view()),
    path('wishlistDelete/<int:pk>/', wishlist_delete),
    path('category/', CategoryView.as_view()),
    path('payment/', PaymentView.as_view()),
    path('order_cart/', OrderCart.as_view()),
    path('book-detail/<int:pk>/', BookDetailView.as_view()),
    path('book_detail/<int:pk>/', BookDetail.as_view()),
    path('saveNote/', SaveNote.as_view()),
    path('cart-item/<str:cartId>/', CartView.as_view()),
    path('book-listing/<int:pk>/', BookListingView.as_view()),
    path('forget_password/', ForgetPasswordView.as_view(), name='forget-password'),
    path('reset-password-confirm/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', ResetPasswordCompleteView.as_view(),name='reset-password-complete'),
    # path('check_user_login/<int:pk>/', BookListingView.as_view()),
]

backend/book_assign/urls.py
from django.urls import path, include
from .views import *

app_name = 'book_assign'

urlpatterns = [
    path('List/', book_assign_list, name="book_assign_list"),
    path('Assign/', book_assign, name="book_assign"),
    path('<int:pk>/delete/',book_assign_delete, name="book_assign_delete"),
    path('<int:pk>/edit/',book_assign_edit, name="book_assign_edit"),
]

backend/user_manager/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('List/', user_list, name="user_list"),
    path('profile/', profile, name="profile"),
    path('signup/', signup, name="signup"),
    path('Create/', UsersCreateView.as_view(), name="users_create"),
    path('update/<int:pk>/', update_signup, name="edit_user"),
    path('delete/<int:pk>/', delete_user, name="delete_user"),
    path('change_password/', change_password, name="change_password"),
]

backend/book_assign/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models
from backend.user_manager.models import User
from backend.book_manager.models import Book


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,
                             related_name='user_%(class)ss')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=True, blank=True,
                             related_name='book_%(class)ss')

    def __str__(self):
        return self.user.first_name

backend/book_assign/views.py
from django.shortcuts import render, redirect, get_object_or_404
from backend.payment.models import Payment
from utilities.utilities import admin_logged
from django.utils.decorators import method_decorator
from backend.payment.forms import Payment_Form
from django.contrib.auth.decorators import login_required
from backend.book_manager.models import Book
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from backend.user_manager.models import User



@admin_logged
@login_required
def book_assign_list(request):
    book_assign_list = Payment.objects.filter(payment_method='assign')
    return render(request, 'book_assign_list.html', {'book_assign_list': book_assign_list, 'book_assign': True})

@admin_logged
@login_required
def book_assign(request):
    book_list = Book.objects.all().values('id', 'title')
    teacher_list = User.objects.filter(user_type=2).values('id', 'first_name', 'last_name')
    payment_form = Payment_Form()
    if request.method == 'POST':
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        payment_form = Payment_Form(request.POST)
        if payment_form.is_valid():
            data = payment_form.save(commit=False)
            data.end_date = end_date
            data.start_date = start_date
            data.payment_method = 'assign'
            data.txn_status = 'Success'
            data.save()
            book = request.POST.getlist('book')
            users = request.POST.getlist('user')
            data.book.set(book)
            data.user.set(users)
            payment_form.save_m2m()
        return redirect('book_assign:book_assign_list')
    else:
        payment_form = Payment_Form()
    return render(request, 'book_assign.html', {'payment_form':payment_form,'teacher_list': teacher_list, 'book_assign': True, 'book_list': book_list})


@admin_logged
@login_required
def book_assign_delete(request,pk):
    Payment.objects.get(pk=pk).delete()
    messages.success(request, 'book assign Deleted successfully.')
    return redirect('book_assign:book_assign_list')

@admin_logged
@login_required
def book_assign_edit(request,pk):
    if Payment.objects.filter(pk=pk).exists():
        data = Payment.objects.get(id=pk)
        payment_form = Payment_Form(instance=data)
        if request.method == 'POST':
            start_date = request.POST.get('start_date')
            end_date = request.POST.get('end_date')
            payment_form = Payment_Form(request.POST,instance = data)
            if payment_form.is_valid():
                data = payment_form.save(commit=False)
                data.end_date = end_date
                data.start_date = start_date
                data.payment_method = 'assign'
                data.txn_status = 'Success'
                data.save()
                book = request.POST.getlist('book')
                users = request.POST.getlist('user')
                data.book.set(book)
                data.user.set(users)
                payment_form.save_m2m()
                messages.success(request, 'book assign updated.')
            return redirect('book_assign:book_assign_list')
    else:
        messages.error(request, 'pk is invalide.')
        return redirect('book_assign:book_assign_list')
    return render(request, 'book_assign.html',
                  {'payment_form': payment_form, 'book_assign': True,'data':data})

backend/book_assign/templates/book_assign.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Book Access{% endblock title %}

{% block content %}
<div class="main_content_iner overly_inner ">
    <div class="container-fluid p-0 ">
        <!-- page title  -->
        <div class="row">
            <div class="col-12">
                <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                    <div class="page_title_left d-flex align-items-center">
                        <h3 class="f_s_25 f_w_700 dark_text mr_30">Book Assign Manageement</h3>
                        <ol class="breadcrumb page_bradcam mb-0">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Home</a></li>
                            <li class="breadcrumb-item active">Book Assign</li>
                        </ol>
                    </div>
<!--                    <div class="page_title_right">-->
<!--                        <div class="page_date_button d-flex align-items-center">-->
<!--                            <img src="{% static 'img/icon/calender_icon.svg' %}" alt=""> August 1, 2020 - August 31, 2020-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
<!--                            <div class="main-title">-->
<!--                                <h3 class="m-0">Basic Form</h3>-->
<!--                            </div>-->
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible fade show">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                </div>
                                {% endfor %}
                             {% endif %}
                        </div>
                    </div>
                    <div class="white_card_body">
                        <form action="" method="post" id="book_assignment">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="start_date">Start Date<span class="text-danger">*</span></label>
                                        <input type="date" name="start_date" id="start_date" required class="form-control datetime">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="end_date">End Date <span class="text-danger">*</span></label>
                                        <input type="date" name="end_date" id="end_date" required class="form-control datetime2">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="book_select">Book Select</label>
                                        <input type="hidden" id="selected_books" value='{{data.book.all|join:"|"}}'>
                                        {{payment_form.book}}
<!--                                        <select name="book_select[]" required id="book_select" class="form-control select2 book_select" multiple>-->
<!--                                            {% for book in book_list %}-->
<!--                                                <option value="{{book.id}}">{{book.title}}</option>-->
<!--                                            {% endfor %}-->
<!--                                        </select>-->
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="role_select">Teacher Select</label>
                                        <input type="hidden" id="selected_teacher" value='{{data.user.all|join:"|"}}'>
                                        {{payment_form.user}}
<!--                                        <select name="role_select[]" id="role_select" required class="form-control select2 user_select" multiple>-->
<!--                                            <option value="">&#45;&#45;&#45;&#45; Select Teacher &#45;&#45;&#45;&#45;</option>-->
<!--                                            {% for i in teacher_list %}-->
<!--                                                <option value="{{i.id}}">{{i.first_name}} {{i.last_name}}</option>-->
<!--                                            {% endfor %}-->
<!--                                        </select>-->
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <input type="submit" class="btn btn-success mt-4">
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block footer %}

<script>
var srat_date = "{{data.start_date|date:"Y-m-d H:i"}}";
var end_date = "{{data.end_date|date:"Y-m-d H:i"}}";
    $(document).ready(function() {

    var selectd_book = $("#selected_books").val();
    var selected_teacher = $("#selected_teacher").val();
    if(selectd_book)
    {
    var select_book_in_array = selectd_book.split("|");
       $("#id_book option").each(function()
        {
          if(select_book_in_array.lastIndexOf($(this).text()) != -1)
          {
                $(this).prop('selected', true);
          }
          if($(this).val()=="")
          {
          $(this).prop('selected', false);
          }
        });
    }

    if(selected_teacher)
    {
    var selected_teacher_in_array = selected_teacher.split("|");
       $("#id_user option").each(function()
        {
          if(selected_teacher_in_array.lastIndexOf($(this).text()) != -1)
          {
                $(this).prop('selected', true);
          }
          if($(this).val()=="")
          {
          $(this).prop('selected', false);
          }
        });
    }

        $('#id_book').select2({
    placeholder: "Please select book"
});
        $('#id_user').select2(
        {
    placeholder: "Please select teacher"
});
        $('.datetime').flatpickr({
            "enableTime": true,
            dateFormat: "Y-m-d H:i",
            defaultDate: [srat_date],
<!--            minDate: "today",-->
<!--            maxDate: new Date().fp_incr(14) // 14 days from now-->
        });


        $('.datetime2').flatpickr({
            "enableTime": true,
            dateFormat: "Y-m-d H:i",
            defaultDate: [end_date],
<!--            minDate: "today",-->
<!--            maxDate: new Date().fp_incr(14) // 14 days from now-->
        });
      });

jQuery.validator.addMethod("dateAfter",
function(value, element, params) {

    if (!/Invalid|NaN/.test(new Date(value))) {
        return new Date(value) > new Date($(params).val());
    }

    return isNaN(value) && isNaN($(params).val())
        || (Number(value) > Number($(params).val()));
},'Must be greater than start date.');

$('#book_assignment').validate({
    rules: {
        start_date: {
            required: true,
        },
        end_date: {
            required: true,
            dateAfter: "#start_date",
        },
        role_select: {
            required: true,
        }
    },
    messages: {
    },
    errorPlacement: function(error, element){
        error.insertAfter(element.parent());
    },
    submitHandler: function() {
        return true
    }
})
</script>
{% endblock %}

backend/book_assign/templates/book_assign_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Report Management{% endblock title %}

{% block content %}
<div class="main_content_iner overly_inner ">
    <div class="container-fluid p-0 ">
        <!-- page title  -->
        <div class="row">
            <div class="col-12">
                <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                    <div class="page_title_left d-flex align-items-center">
                        <h3 class="f_s_25 f_w_700 dark_text mr_30">Book Assignment</h3>
                        <ol class="breadcrumb page_bradcam mb-0">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Home</a></li>
                            <li class="breadcrumb-item active">Book Assignment</li>
                             <li class="breadcrumb-item active">Book Assignment Listing</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="white_card card_height_100 mb_30 pt-4">
                    <div class="white_card_body">
                        <div class="QA_section">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible fade show">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                </div>
                                {% endfor %}
                             {% endif %}
                            <div class="white_box_tittle list_header">
                                <div class="col-xl-4">
                                    <h4>Book Assignment List </h4>
                                </div>
                                <div class="box_right d-flex lms_block col-xl-6">
                                    <div class="serach_field_2">
                                        <div class="search_inner">
                                            <form Active="#">
                                                <div class="search_field">
                                                    <input type="text" placeholder="Search content here...">
                                                </div>
                                                <button type="submit"> <i class="ti-search"></i> </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="add_button ml-10">
                                        <a href="#" data-toggle="modal" data-target="#addcategory" class="btn_1">search</a>
                                    </div>
                                    <div class="add_button ml-10">
                                        <a href="{% url 'book_assign:book_assign' %}" class="btn_1">Book Assign</a>
                                    </div>
                                </div>
<!--                                <div class="1col-xl-2">-->
<!--                                    <a href="{% url 'users:signup' %}" class="btn btn-primary float-right">Create User</a>-->
<!--                                </div>-->
                            </div>

                            <div class="QA_table mb_30">
                                <!-- table-responsive -->
                                <table class="table lms_table_active ">
                                    <thead>
                                        <tr>
                                            <th scope="col">S.no</th>
                                            <th scope="col">Teacher Name</th>
                                            <th scope="col">Book Name</th>
                                            <th scope="col">Email</th>
                                            <th scope="col">Start Date</th>
                                            <th scope="col">End Date</th>
                                            <th scope="col">Payment Method</th>
                                            <th scope="col">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for report in book_assign_list %}
                                          <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <th scope="row">{{report.user.all|join:" | "}}</th>
                                            <th scope="row">{{report.book.all|join:" | "}}</th>
                                            <th scope="row">{{report.user.email}}</th>
                                            <th scope="row">{{report.start_date|date:"d,M Y h:i a"}}</th>
                                            <th scope="row">{{report.end_date|date:"d,M Y h:i a"}}</th>
                                            <th scope="row">{{report.payment_method}}</th>
                                            <th scope="row">
                                                <div class="action_btns d-flex">
                                                        <a href="{% url 'book_assign:book_assign_edit' report.id  %}" class="action_btn mr_10"><i class="far fa-edit"></i></a>
                                                        <a href="{% url 'book_assign:book_assign_delete' report.id  %}" class="action_btn" onclick="return confirm('Are you sure you want to delete this item?');">
                                                              <i class="fas fa-trash"></i>
                                                        </a>
                                                    </div>
                                            </th>
                                          </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}