agnito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.views import BookDocumentView

admin.site.site_header = "Agnito"
admin.site.site_title = "Agnito"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('superadmin/', include('backend.backend.urls')),
    path('admin-login/', include('login.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('search/', BookDocumentView.as_view({'get': 'list'})),
    path('accounts/', include('allauth.urls')), ### allauth
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from os import name
from django.urls import path, include
from .views import *

urlpatterns = [
    path('contact/', ContactView.as_view()),
    path('login/', LoginView.as_view()),
    path('signup/', SignupView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('social_signup/', SocialSignupView.as_view()),
    path('library/<int:user_id>', LibraryView.as_view()),
    path('library/', LibraryView.as_view()),
    path('popular/', PopularView.as_view()),
    path('banner/', BannerView.as_view()),
    path('wishlist/<int:user_id>/', WishlistView.as_view()),
    path('wishlistAdd/', WishlistView.as_view()),
    path('wishlistDelete/<int:pk>/', wishlist_delete),
    path('category/', CategoryView.as_view()),
    path('payment/', PaymentView.as_view()),
    path('order_cart/', OrderCart.as_view()),
    path('book-detail/<int:pk>/', BookDetailView.as_view()),
    path('book_detail/<int:pk>/', BookDetail.as_view()),
    path('saveNote/', SaveNote.as_view()),
    path('cart-item/<str:cartId>/', CartView.as_view()),
    path('book-listing/<int:pk>/', BookListingView.as_view()),
    path('forget_password/', ForgetPasswordView.as_view(), name='forget-password'),
    path('reset-password-confirm/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', ResetPasswordCompleteView.as_view(),name='reset-password-complete'),
    # path('check_user_login/<int:pk>/', BookListingView.as_view()),
]

backend/contact/urls.py
from django.urls import path, include
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('List/', ContactListView.as_view(), name="contact_list"),
]

backend/user_manager/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('List/', user_list, name="user_list"),
    path('profile/', profile, name="profile"),
    path('signup/', signup, name="signup"),
    path('Create/', UsersCreateView.as_view(), name="users_create"),
    path('update/<int:pk>/', update_signup, name="edit_user"),
    path('delete/<int:pk>/', delete_user, name="delete_user"),
    path('change_password/', change_password, name="change_password"),
]

backend/contact/models.py
from django.db import models

ENQUIRY_TYPE = ((1, 'Interview'), (2, 'Sale'))


class ContactUs(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    mobile = models.CharField(max_length=150)
    enquiry_type = models.IntegerField(choices=ENQUIRY_TYPE)
    email = models.CharField(max_length=150)
    company_name = models.CharField(max_length=150, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

backend/contact/views.py
from django.shortcuts import render
from .models import ContactUs
from django.views import View
from utilities.utilities import admin_logged
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class ContactListView(View):

    @method_decorator(admin_logged)
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        template_name = 'contact_list.html'
        contact_list = ContactUs.objects.all()
        context = {'contact_list': contact_list, 'contact': True}
        return render(request, template_name, context)

backend/contact/templates/contact_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Contact{% endblock title %}

{% block content %}
<div class="main_content_iner overly_inner ">
    <div class="container-fluid p-0 ">
        <!-- page title  -->
        <div class="row">
            <div class="col-12">
                <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                    <div class="page_title_left d-flex align-items-center">
                        <h3 class="f_s_25 f_w_700 dark_text mr_30">Contact</h3>
                        <ol class="breadcrumb page_bradcam mb-0">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Home</a></li>
                            <li class="breadcrumb-item active">Contact Listing</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">

                <div class="white_card card_height_100 mb_30 pt-4">
                    <div class="white_card_body">
                        <div class="QA_section">
                            {% if messages %}
                                {% for message in messages %}
                                <div class="alert {{ message.tags }} alert-dismissible fade show">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                </div>
                                {% endfor %}
                             {% endif %}
                            <div class="white_box_tittle list_header">
                                <div class="col-xl-6">
                                    <h4>Contacts List </h4>
                                </div>
                                <div class="box_right d-flex lms_block col-xl-4">
                                    <div class="serach_field_2">
                                        <div class="search_inner">
                                            <form Active="#">
                                                <div class="search_field">
                                                    <input type="text" placeholder="Search content here...">
                                                </div>
                                                <button type="submit"> <i class="ti-search"></i> </button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="add_button ml-10">
                                        <a href="#" data-toggle="modal" data-target="#addcategory" class="btn_1">search</a>
                                    </div>
                                </div>
<!--                                <div class="1col-xl-2">-->
<!--                                    <a href="{% url 'users:signup' %}" class="btn btn-primary float-right">Create User</a>-->
<!--                                </div>-->
                            </div>

                            <div class="QA_table mb_30">
                                <!-- table-responsive -->
                                <table class="table lms_table_active ">
                                    <thead>
                                        <tr>
                                            <th scope="col">S.no</th>
                                            <th scope="col">Full Name</th>
                                            <th scope="col">Contact Number</th>
                                            <th scope="col">Email Address</th>
                                            <th scope="col">Enquiry Type</th>
                                            <th scope="col">Company Name</th>
                                            <th scope="col">Date</th>
                                            <th scope="col">View Message</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for con in contact_list %}
                                          <tr>
                                            <th scope="row">{{forloop.counter}}</th>
                                            <th scope="row">{{con.get_full_name|default_if_none:'-'}}</th>
                                            <th scope="row">{{con.mobile|default_if_none:'-'}}</th>
                                            <th scope="row">{{con.email|default_if_none:'-'}}</th>
                                            <th scope="row">{{con.get_enquiry_type_display|default_if_none:'-'}}</th>
                                            <th scope="row">{{con.company_name|default_if_none:'-'}}</th>
                                            <th scope="row">{{con.created_at|default_if_none:'-'}}</th>
                                            <th scope="row">
                                                <span style="display: none;">{{con.message|default_if_none:'-'}}</span>
                                                <i class="fa fa-eye view_msg" id="view_msg" data-msg="{{con.message|default_if_none:'-'}}"></i></th>
                                          </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>

<div class="modal" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Message</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">

            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

          </div>
        </div>
      </div>


{% endblock %}
 {% block footer %}
<script>
    $('.view_msg').click(function() {
        var msg = $(this).data('msg');
        $('.modal-body').text(msg);
       $('#myModal').modal('show');
    });
</script>
{% endblock footer %}