agnito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.views import BookDocumentView

admin.site.site_header = "Agnito"
admin.site.site_title = "Agnito"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('superadmin/', include('backend.backend.urls')),
    path('admin-login/', include('login.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('search/', BookDocumentView.as_view({'get': 'list'})),
    path('accounts/', include('allauth.urls')), ### allauth
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from os import name
from django.urls import path, include
from .views import *

urlpatterns = [
    path('contact/', ContactView.as_view()),
    path('login/', LoginView.as_view()),
    path('signup/', SignupView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('social_signup/', SocialSignupView.as_view()),
    path('library/<int:user_id>', LibraryView.as_view()),
    path('library/', LibraryView.as_view()),
    path('popular/', PopularView.as_view()),
    path('banner/', BannerView.as_view()),
    path('wishlist/<int:user_id>/', WishlistView.as_view()),
    path('wishlistAdd/', WishlistView.as_view()),
    path('wishlistDelete/<int:pk>/', wishlist_delete),
    path('category/', CategoryView.as_view()),
    path('payment/', PaymentView.as_view()),
    path('order_cart/', OrderCart.as_view()),
    path('book-detail/<int:pk>/', BookDetailView.as_view()),
    path('book_detail/<int:pk>/', BookDetail.as_view()),
    path('saveNote/', SaveNote.as_view()),
    path('cart-item/<str:cartId>/', CartView.as_view()),
    path('book-listing/<int:pk>/', BookListingView.as_view()),
    path('forget_password/', ForgetPasswordView.as_view(), name='forget-password'),
    path('reset-password-confirm/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', ResetPasswordCompleteView.as_view(),name='reset-password-complete'),
    # path('check_user_login/<int:pk>/', BookListingView.as_view()),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = (
    path("", Login, name="admin_login"),
)

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def Login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("superadmin")
        else:
            messages.info(request, "Username Or Password Incorrect")
    context = {}
    if request.user.is_authenticated:
        return redirect("superadmin")
    return render(request, "login.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock%}</title>

    <style>
       {% block style %}
       {% endblock %}
    </style>
</head>
<body>
{% block body %}

{% endblock %}


{% block script %}
{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}

{% block content %}
<div class="main_content_iner overly_inner ">
<div class="container-fluid p-0 ">
    <!-- page title  -->
    <div class="row">
        <div class="col-12">
            <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                <div class="page_title_left d-flex align-items-center">
                    <h3 class="f_s_25 f_w_700 dark_text mr_30">Dashboard</h3>
                    <ol class="breadcrumb page_bradcam mb-0">
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Home</a></li>
                        <li class="breadcrumb-item active">Analytic</li>
                    </ol>
                </div>

            </div>
        </div>
    </div>
    <div class="row ">

       
    </div>
</div>
</div>

{% endblock content %}

templates/error_400.html
<!DOCTYPE html>
<html lang="zxx">


<!-- Mirrored from demo.dashboardpack.com/user-management-html/error_400.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 27 Aug 2021 09:45:41 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<!-- /Added by HTTrack -->

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Management Admin</title>

    <!-- <link rel="icon" href="img/favicon.png" type="image/png"> -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <!-- themefy CSS -->
    <link rel="stylesheet" href="vendors/themefy_icon/themify-icons.css" />
    <!-- swiper slider CSS -->
    <link rel="stylesheet" href="vendors/swiper_slider/css/swiper.min.html" />
    <!-- select2 CSS -->
    <link rel="stylesheet" href="vendors/select2/css/select2.min.html" />
    <!-- select2 CSS -->
    <link rel="stylesheet" href="vendors/niceselect/css/nice-select.css" />
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="vendors/owl_carousel/css/owl.carousel.css" />
    <!-- gijgo css -->
    <link rel="stylesheet" href="vendors/gijgo/gijgo.min.css" />
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="vendors/font_awesome/css/all.min.css" />
    <link rel="stylesheet" href="vendors/tagsinput/tagsinput.css" />

    <!-- date picker -->
    <link rel="stylesheet" href="vendors/datepicker/date-picker.css" />

    <!-- datatable CSS -->
    <link rel="stylesheet" href="vendors/datatable/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="vendors/datatable/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" href="vendors/datatable/css/buttons.dataTables.min.css" />
    <!-- text editor css -->
    <link rel="stylesheet" href="vendors/text_editor/summernote-bs4.css" />
    <!-- morris css -->
    <link rel="stylesheet" href="vendors/morris/morris.css">
    <!-- metarial icon css -->
    <link rel="stylesheet" href="vendors/material_icon/material-icons.css" />

    <!-- menu css  -->
    <link rel="stylesheet" href="css/metisMenu.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="css/colors/default.css" id="colorSkinCSS">
</head>

<body>

    <div class="erroe_page_wrapper">
        <div class="errow_wrap">
            <div class="container text-center">
                <img src="img/bak_hovers/sad.png" alt="">
                <div class="error_heading  text-center">
                    <h3 class="headline font-danger theme_color_6">404</h3>
                </div>
                <div class="col-md-8 offset-md-2 text-center">
                    <p>The page you are attempting to reach is currently not available. This may be because the page does not exist or has been moved.</p>
                </div>
                <div class="error_btn  text-center">
                    <a class=" default_btn theme_bg_6 " href="index.html">Back Home</a>
                </div>
            </div>
        </div>
    </div>

    <!-- footer  -->
    <!-- jquery slim -->
    <script src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="js/popper.min.js"></script>
    <!-- bootstarp js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- sidebar menu  -->

</body>

<!-- Mirrored from demo.dashboardpack.com/user-management-html/error_400.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 27 Aug 2021 09:45:42 GMT -->

</html>

templates/error_500.html
<!DOCTYPE html>
<html lang="zxx">


<!-- Mirrored from demo.dashboardpack.com/user-management-html/error_500.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 27 Aug 2021 09:45:42 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<!-- /Added by HTTrack -->

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Management Admin</title>

    <!-- <link rel="icon" href="img/favicon.png" type="image/png"> -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <!-- themefy CSS -->
    <link rel="stylesheet" href="vendors/themefy_icon/themify-icons.css" />
    <!-- swiper slider CSS -->
    <link rel="stylesheet" href="vendors/swiper_slider/css/swiper.min.html" />
    <!-- select2 CSS -->
    <link rel="stylesheet" href="vendors/select2/css/select2.min.html" />
    <!-- select2 CSS -->
    <link rel="stylesheet" href="vendors/niceselect/css/nice-select.css" />
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="vendors/owl_carousel/css/owl.carousel.css" />
    <!-- gijgo css -->
    <link rel="stylesheet" href="vendors/gijgo/gijgo.min.css" />
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="vendors/font_awesome/css/all.min.css" />
    <link rel="stylesheet" href="vendors/tagsinput/tagsinput.css" />

    <!-- date picker -->
    <link rel="stylesheet" href="vendors/datepicker/date-picker.css" />

    <!-- datatable CSS -->
    <link rel="stylesheet" href="vendors/datatable/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="vendors/datatable/css/responsive.dataTables.min.css" />
    <link rel="stylesheet" href="vendors/datatable/css/buttons.dataTables.min.css" />
    <!-- text editor css -->
    <link rel="stylesheet" href="vendors/text_editor/summernote-bs4.css" />
    <!-- morris css -->
    <link rel="stylesheet" href="vendors/morris/morris.css">
    <!-- metarial icon css -->
    <link rel="stylesheet" href="vendors/material_icon/material-icons.css" />

    <!-- menu css  -->
    <link rel="stylesheet" href="css/metisMenu.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="css/colors/default.css" id="colorSkinCSS">
</head>

<body>

    <div class="erroe_page_wrapper">
        <div class="errow_wrap">
            <div class="container text-center">
                <img src="img/bak_hovers/sad.png" alt="">
                <div class="error_heading  text-center">
                    <h3 class="headline color_parpel2">500</h3>
                </div>
                <div class="col-md-8 offset-md-2 text-center">
                    <p>The page you are attempting to reach is currently not available. This may be because the page does not exist or has been moved.</p>
                </div>
                <div class="error_btn  text-center">
                    <a class=" default_btn parpel_bg2 " href="index.html">Back Home</a>
                </div>
            </div>
        </div>
    </div>

    <!-- footer  -->
    <!-- jquery slim -->
    <script src="js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="js/popper.min.js"></script>
    <!-- bootstarp js -->
    <script src="js/bootstrap.min.js"></script>
    <!-- sidebar menu  -->

</body>

<!-- Mirrored from demo.dashboardpack.com/user-management-html/error_500.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 27 Aug 2021 09:45:42 GMT -->

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="csrf-token" content="lVbCfqxAwD3YVqtRhqMEKpApGogTj4ebn28uR8Na">
  <title>Login</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
  <!-- Bootstrap core CSS -->
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>
<body class="grey lighten-3">
<!--Main layout-->
    <div class="container-fluid mt-5">
      <div class="col-md-12 col-lg-6 col-xl-4 mx-auto mb-4">
        <section class="form-gradient">
            <div class="card z-depth-5" style="margin-top: 150px;">
                <!--Header-->
                <div class="header pt-3 danger-color">

                    <div class="row d-flex justify-content-center">
                        <h3 class="white-text mb-3 pt-3 font-weight-bold"><i class="far fa-user"></i>&nbsp;SCS Admin Login</h3>
                    </div>
                </div>
                <!--Header-->
                <div class="card-body mx-4 mt-4">
                    <!--Body-->
                     <!--Grid row-->
                        {% for msg in messages %}
                        <p style="color:red">Warning : {{msg}}</p>
                        {% endfor %}
                    <form method="POST" action="{% url 'login:admin_login' %}" class="form-signin">
                         {% csrf_token %}
                         <div class="md-form">
                             <!--<label for="Form-email3">Email Id</label>-->
                            <input id="email" type="email" class="form-control" placeholder="Email Please" title="Enter your email Please"  name="email" value="" autocomplete="off" required autofocus>

                        </div>
                        <div class="md-form">
                           <!-- <label for="Form-pass3">Password</label>-->
                            <input id="password" type="password" class="form-control" name="password" autocomplete="off" placeholder="Password Please" title="Enter your password Please"  required>

                        </div>
                        <br>

                        <div class="row d-flex mb-4">
                            <!--Grid column-->
                            <div class="text-center mb-3 col-md-12">
                                <button type="submit" class="btn btn-danger btn-block z-depth-1 waves-effect waves-light">LOGIN</button>
                            </div>
                            <!--Grid column-->
                        </div>
                    </form>
                </div>
            </div>
        </section>

      </div>
    </div>
  <!--Main layout-->
  <!-- JQuery -->
  <script type="text/javascript" src="http://ovecrm.developersoptimal.com/assets/js/jquery-3.3.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="http://ovecrm.developersoptimal.com/assets/js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="http://ovecrm.developersoptimal.com/assets/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="http://ovecrm.developersoptimal.com/assets/js/nmdb.min.js"></script>
  <!-- DataTables JS -->

<script type="text/javascript">
  // Animations initialization
    new WOW().init();
  $(document).ready(function () {

});
</script>
</body>
<!--
<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpbh'},{'server':'sg3plvcpnl357299'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script></html>-->